#!/bin/bash

# Netlify Manual Deploy Helper
# This script outputs the exact steps to manually deploy each app

echo "=========================================="
echo "  MODULE FEDERATION DEPLOYMENT GUIDE"
echo "=========================================="
echo ""
echo "All apps have been built successfully:"
echo ""
echo "1. Contacts App"
echo "   Site: taupe-sprinkles-83c9ee"
echo "   URL: https://contacts.smartcrm.vip"
echo "   Dist: /workspaces/crm-smartreplit/apps/contacts/dist/"
echo "   Deploy: https://app.netlify.com/projects/taupe-sprinkles-83c9ee"
echo ""
echo "2. Pipeline App"
echo "   Site: cheery-syrniki-b5b6ca"
echo "   URL: https://pipeline.smartcrm.vip"
echo "   Dist: /workspaces/crm-smartreplit/apps/pipeline/dist/"
echo "   Deploy: https://app.netlify.com/projects/cheery-syrniki-b5b6ca"
echo ""
echo "3. Analytics App"
echo "   Site: subtle-florentine-8fd315"
echo "   URL: https://analytics.smartcrm.vip"
echo "   Dist: /workspaces/crm-smartreplit/apps/analytics/dist/"
echo "   Deploy: https://app.netlify.com/projects/subtle-florentine-8fd315"
echo ""
echo "4. Calendar App"
echo "   Site: voluble-vacherin-add80d"
echo "   URL: https://calendar.smartcrm.vip"
echo "   Dist: /workspaces/crm-smartreplit/apps/calendar/dist/"
echo "   Deploy: https://app.netlify.com/projects/voluble-vacherin-add80d"
echo ""
echo "=========================================="
echo "  DEPLOYMENT STEPS (for each app)"
echo "=========================================="
echo ""
echo "1. Go to the deploy URL listed above"
echo "2. Click 'Deploy' → 'Deploy manually'"
echo "3. Drag & drop the entire 'dist' folder"
echo "4. Wait for deployment to complete"
echo "5. Verify: the production URL matches the custom domain"
echo ""
echo "After all 4 are deployed, test:"
echo "  node /workspaces/crm-smartreplit/test-mfe-integration.js"
echo ""
echo "=========================================="
