import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import prettierConfig from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        process: 'readonly',
        localStorage: 'readonly',
        setTimeout: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Buffer: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        alert: 'readonly',
        navigator: 'readonly',
        // Additional browser globals
        HTMLIFrameElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLAudioElement: 'readonly',
        Node: 'readonly',
        NodeJS: 'readonly',
        File: 'readonly',
        Blob: 'readonly',
        MediaStream: 'readonly',
        MediaRecorder: 'readonly',
        ClipboardEvent: 'readonly',
        MouseEvent: 'readonly',
        MessageEvent: 'readonly',
        AbortSignal: 'readonly',
        AbortController: 'readonly',
        // Encoding functions
        atob: 'readonly',
        btoa: 'readonly',
        // Test globals
        vi: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      '@typescript-eslint/no-unused-vars': ['warn', { 
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        ignoreRestSiblings: true
      }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-empty-function': 'warn',
    },
  },
  // CommonJS files (.cjs) with Node.js globals
  {
    files: ['**/*.cjs'],
    languageOptions: {
      globals: {
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        console: 'readonly',
        process: 'readonly',
        global: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        alert: 'readonly',
      },
    },
  },
  // JavaScript files with browser globals
  {
    files: ['client/public/**/*.js'],
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        alert: 'readonly',
      },
    },
  },
  {
    files: ['client/src/**/*.{ts,tsx}'],
    plugins: {
      react,
      'react-hooks': reactHooks,
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react/display-name': 'off',
      'react/no-unstable-nested-components': 'off',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  prettierConfig,
  {
    ignores: [
      'dist/**', 
      'node_modules/**', 
      'netlify/**',
      '*.config.js', 
      '*.config.ts',
      'calendar-mf-setup/**',
      '.agents/**',
      '.husky/**',
      '.roo/**',
      'attached_assets/**',
      'server/**',
      'check-*.js',
      '*.test.cjs',
      'client/check-*.js',
      'client/public/iframe-overlap-fix.js',
      'client/public/landing-page-navigation-script.js',
      'client/src/*FeaturePage*.tsx',
      'client/src/Pasted-*.txt',
      'client/src/*.png',
      'client/test-*.js',
      'vite-host-override.js',
      'vite-patch.js',
      'fix-vite-hosts.js',
      'final-vite-fix.js',
      'start-dev.js',
      'build.sh',
      'build-server.sh',
      'deploy-functions.js',
      'fix-admin-access.js',
      'restore-keith.js',
      'invite-keith.js',
      'set-keith-password.js',
      'check-users.js',
      'check-admin-status.js',
      'send_admin_confirmations.js',
      'simple-navigation-integration.js',
      'integration-code.js',
      'social-media-api-helper.js',
      'gpt5-social-research-service.js',
      'remote-navigation-bridge.js',
      'remote-pipeline-integration.js',
    ],
  },
];
