allowBuilds:
  '@parcel/watcher': set this to true or false
  bufferutil: set this to true or false
  canvas: set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  netlify-cli: set this to true or false
  puppeteer: set this to true or false
  sharp: set this to true or false
  unix-dgram: set this to true or false
