import { db } from '../server/db';
import { features } from '../shared/schema';

/**
 * Comprehensive SmartCRM Feature List
 * Organized by category with hierarchical structure
 */
const comprehensiveFeatures = [
  // ===== CORE CRM FEATURES =====
  {
    featureKey: 'core_crm',
    name: 'Core CRM',
    description: 'Essential CRM functionality',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'dashboard',
    name: 'Dashboard',
    description: 'Main CRM dashboard with KPIs',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'contacts',
    name: 'Contacts',
    description: 'Contact management system',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'pipeline',
    name: 'Pipeline',
    description: 'Sales pipeline and deal tracking',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'calendar',
    name: 'Calendar',
    description: 'Calendar and scheduling',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'tasks',
    name: 'Tasks',
    description: 'Task management and tracking',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'tasks.board',
    name: 'Task Board',
    description: 'Kanban-style task board',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'tasks.calendar',
    name: 'Task Calendar',
    description: 'Calendar view for tasks',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'tasks.analytics',
    name: 'Task Analytics',
    description: 'Task performance analytics',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'appointments',
    name: 'Appointments',
    description: 'Appointment scheduling and management',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'analytics',
    name: 'Analytics',
    description: 'Business analytics and reporting',
    category: 'core_crm',
    deliveryType: 'native',
    isEnabled: true,
  },

  // ===== SALES INTELLIGENCE =====
  {
    featureKey: 'sales_intelligence',
    name: 'Sales Intelligence',
    description: 'Advanced sales analytics and insights',
    category: 'sales_intelligence',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'deal_pipeline_analytics',
    name: 'Pipeline Intelligence',
    description: 'Deep pipeline analytics',
    category: 'sales_intelligence',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'deal_risk_monitor',
    name: 'Deal Risk Monitor',
    description: 'Monitor at-risk deals',
    category: 'sales_intelligence',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'conversion_insights',
    name: 'Conversion Insights',
    description: 'Conversion rate analytics',
    category: 'sales_intelligence',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'pipeline_health',
    name: 'Pipeline Health Dashboard',
    description: 'Overall pipeline health metrics',
    category: 'sales_intelligence',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'sales_cycle_analytics',
    name: 'Sales Cycle Analytics',
    description: 'Analyze sales cycle duration',
    category: 'sales_intelligence',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'win_rate_analysis',
    name: 'Win Rate Intelligence',
    description: 'Win/loss rate analysis',
    category: 'sales_intelligence',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'revenue_intelligence',
    name: 'Revenue Intelligence',
    description: 'Revenue forecasting and analysis',
    category: 'sales_intelligence',
    deliveryType: 'native',
    isEnabled: true,
  },

  // ===== AI FEATURES - CORE =====
  {
    featureKey: 'ai_features',
    name: 'AI Features',
    description: 'Artificial intelligence powered features',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_goals',
    name: 'AI Goals',
    description: 'AI-powered goal setting and tracking',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools',
    name: 'AI Tools',
    description: 'Suite of AI productivity tools',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },

  // AI Tools - Core AI Tools
  {
    featureKey: 'ai_tools.email_analysis',
    name: 'Email Analysis',
    description: 'AI-powered email analysis',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.meeting_summary',
    name: 'Meeting Summarizer',
    description: 'Auto-generate meeting summaries',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.proposal_generator',
    name: 'Proposal Generator',
    description: 'Create professional proposals',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.call_scripts',
    name: 'Call Script Generator',
    description: 'Generate sales call scripts',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.subject_optimizer',
    name: 'Subject Line Optimizer',
    description: 'Generate compelling subject lines',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.competitor_analysis',
    name: 'Competitor Analysis',
    description: 'Analyze competitors',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.market_trends',
    name: 'Market Trends',
    description: 'Market intelligence and trends',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.sales_insights',
    name: 'Sales Insights',
    description: 'Sales performance insights',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.sales_forecast',
    name: 'AI Sales Forecast',
    description: 'Predictive sales forecasting',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },

  // AI Tools - Communication
  {
    featureKey: 'ai_tools.email_composer',
    name: 'Email Composer',
    description: 'AI email writing assistant',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.objection_handler',
    name: 'Objection Handler',
    description: 'Handle sales objections',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.email_response',
    name: 'Email Response Generator',
    description: 'Generate email responses',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.voice_tone_optimizer',
    name: 'Voice Tone Optimizer',
    description: 'Optimize communication tone',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },

  // AI Tools - Customer & Content
  {
    featureKey: 'ai_tools.customer_persona',
    name: 'Customer Persona Builder',
    description: 'Build customer personas',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.visual_content',
    name: 'Visual Content Generator',
    description: 'Generate visual content',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.meeting_agenda',
    name: 'Meeting Agenda Generator',
    description: 'Create meeting agendas',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },

  // AI Tools - Advanced Features
  {
    featureKey: 'ai_tools.assistant',
    name: 'AI Assistant',
    description: 'Conversational AI assistant',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.vision_analyzer',
    name: 'Vision Analyzer',
    description: 'AI image/document analysis',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.image_generator',
    name: 'Image Generator',
    description: 'AI image creation',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.smart_search_realtime',
    name: 'Semantic Search',
    description: 'Intelligent real-time search',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.function_assistant',
    name: 'Function Assistant',
    description: 'Code generation assistant',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },

  // AI Tools - Real-time Features
  {
    featureKey: 'ai_tools.streaming_chat',
    name: 'Streaming Chat',
    description: 'Real-time AI chat streaming',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.form_validation',
    name: 'AI Form Validation',
    description: 'Intelligent form validation',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.live_deal_analysis',
    name: 'Live Deal Analysis',
    description: 'Real-time deal insights',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.instant_response',
    name: 'Instant Response',
    description: 'Instant AI responses',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.realtime_email_composer',
    name: 'Real-time Email Composer',
    description: 'Live email composition',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.voice_analysis_realtime',
    name: 'Voice Analysis Real-time',
    description: 'Real-time voice analysis',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },

  // AI Tools - Reasoning Generators
  {
    featureKey: 'ai_tools.reasoning_email',
    name: 'Reasoning Email',
    description: 'Advanced reasoning email generation',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.reasoning_proposal',
    name: 'Reasoning Proposal',
    description: 'Advanced reasoning proposals',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.reasoning_script',
    name: 'Reasoning Script',
    description: 'Advanced reasoning call scripts',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.reasoning_objection',
    name: 'Reasoning Objection',
    description: 'Advanced reasoning objection handling',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.reasoning_social',
    name: 'Reasoning Social',
    description: 'Advanced reasoning social posts',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },

  // AI Tools - Analysis & Intelligence
  {
    featureKey: 'ai_tools.sentiment_analysis',
    name: 'Sentiment Analysis',
    description: 'Analyze customer sentiment',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.churn_prediction',
    name: 'Churn Prediction',
    description: 'Predict customer churn risk',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },

  // AI Tools - Automation
  {
    featureKey: 'ai_tools.task_automation',
    name: 'Task Automation',
    description: 'Automate repetitive tasks',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.smart_prioritization',
    name: 'Smart Prioritization',
    description: 'AI task prioritization',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'ai_tools.workflow_builder',
    name: 'Workflow Builder',
    description: 'Build automated workflows',
    category: 'ai_features',
    deliveryType: 'native',
    isEnabled: true,
  },

  // ===== COMMUNICATION & REVENUE TOOLS =====
  {
    featureKey: 'communication',
    name: 'Communication Hub',
    description: 'Unified communication platform',
    category: 'communication',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'video_email',
    name: 'Video Email',
    description: 'Send personalized video emails',
    category: 'communication',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'sms_automation',
    name: 'SMS Automation',
    description: 'Automated text messaging',
    category: 'communication',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'voip_phone',
    name: 'VoIP Phone System',
    description: 'Professional calling system',
    category: 'communication',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'invoicing',
    name: 'Invoicing & Billing',
    description: 'Invoice and payment management',
    category: 'communication',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'lead_automation',
    name: 'Lead Automation',
    description: 'Automated lead nurturing workflows',
    category: 'communication',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'circle_prospecting',
    name: 'Circle Prospecting',
    description: 'Geo-targeted prospecting',
    category: 'communication',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'forms_surveys',
    name: 'Forms & Surveys',
    description: 'Create and manage forms',
    category: 'communication',
    deliveryType: 'native',
    isEnabled: true,
  },

  // ===== REMOTE APPS / MODULE FEDERATION =====
  {
    featureKey: 'remote_apps',
    name: 'Remote Apps',
    description: 'External integrated applications',
    category: 'remote_apps',
    deliveryType: 'module_federation',
    isEnabled: true,
  },
  {
    featureKey: 'remote_apps.funnelcraft',
    name: 'FunnelCraft AI',
    description: 'AI-powered funnel building',
    category: 'remote_apps',
    deliveryType: 'iframe',
    isEnabled: true,
  },
  {
    featureKey: 'remote_apps.smartcrm_closer',
    name: 'SmartCRM Closer',
    description: 'Advanced sales closing tools',
    category: 'remote_apps',
    deliveryType: 'iframe',
    isEnabled: true,
  },
  {
    featureKey: 'remote_apps.content_ai',
    name: 'ContentAI',
    description: 'AI content generation platform',
    category: 'remote_apps',
    deliveryType: 'iframe',
    isEnabled: true,
  },
  {
    featureKey: 'remote_apps.pipeline',
    name: 'Remote Pipeline',
    description: 'Remote pipeline module',
    category: 'remote_apps',
    deliveryType: 'module_federation',
    isEnabled: true,
  },
  {
    featureKey: 'remote_apps.contacts',
    name: 'Remote Contacts',
    description: 'Remote contacts module',
    category: 'remote_apps',
    deliveryType: 'module_federation',
    isEnabled: true,
  },
  {
    featureKey: 'remote_apps.calendar',
    name: 'Remote Calendar',
    description: 'Remote calendar module',
    category: 'remote_apps',
    deliveryType: 'module_federation',
    isEnabled: true,
  },
  {
    featureKey: 'remote_apps.analytics',
    name: 'AI Analytics Dashboard',
    description: 'Remote analytics module',
    category: 'remote_apps',
    deliveryType: 'module_federation',
    isEnabled: true,
  },
  {
    featureKey: 'remote_apps.product_research',
    name: 'Product Research',
    description: 'Product research tools',
    category: 'remote_apps',
    deliveryType: 'module_federation',
    isEnabled: true,
  },
  {
    featureKey: 'remote_apps.business_intel',
    name: 'Business Intelligence',
    description: 'Remote business intelligence',
    category: 'remote_apps',
    deliveryType: 'module_federation',
    isEnabled: true,
  },
  {
    featureKey: 'remote_apps.ai_goals',
    name: 'Remote AI Goals',
    description: 'Remote AI goals module',
    category: 'remote_apps',
    deliveryType: 'module_federation',
    isEnabled: true,
  },

  // ===== WHITE LABEL & PARTNER =====
  {
    featureKey: 'white_label',
    name: 'White Label Suite',
    description: 'White label customization features',
    category: 'white_label',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'white_label.customization',
    name: 'White Label Customization',
    description: 'Brand customization tools',
    category: 'white_label',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'white_label.management',
    name: 'WL Management Dashboard',
    description: 'Manage white label settings',
    category: 'white_label',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'white_label.revenue_sharing',
    name: 'Revenue Sharing',
    description: 'Revenue sharing system',
    category: 'white_label',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'white_label.package_builder',
    name: 'Package Builder',
    description: 'Build custom packages',
    category: 'white_label',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'white_label.partner_dashboard',
    name: 'Partner Dashboard',
    description: 'Partner management interface',
    category: 'white_label',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'white_label.partner_onboarding',
    name: 'Partner Onboarding',
    description: 'Onboard new partners',
    category: 'white_label',
    deliveryType: 'native',
    isEnabled: true,
  },

  // ===== ADMIN & GOVERNANCE =====
  {
    featureKey: 'admin',
    name: 'Admin Features',
    description: 'Administrative functions',
    category: 'admin',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'admin.dashboard',
    name: 'Admin Dashboard',
    description: 'Administrative overview',
    category: 'admin',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'admin.user_management',
    name: 'User Management',
    description: 'Manage system users',
    category: 'admin',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'admin.bulk_import',
    name: 'Bulk Import',
    description: 'Bulk user import',
    category: 'admin',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'admin.feature_management',
    name: 'Feature Management',
    description: 'Manage system features',
    category: 'admin',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'admin.analytics',
    name: 'Admin Analytics',
    description: 'System-wide analytics',
    category: 'admin',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'admin.settings',
    name: 'Admin Settings',
    description: 'System configuration',
    category: 'admin',
    deliveryType: 'native',
    isEnabled: true,
  },

  // ===== CONTENT & BUSINESS TOOLS =====
  {
    featureKey: 'content_tools',
    name: 'Content Tools',
    description: 'Content creation and management',
    category: 'business_tools',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'content_library',
    name: 'Content Library',
    description: 'Manage content assets',
    category: 'business_tools',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'voice_profiles',
    name: 'Voice Profiles',
    description: 'Voice synthesis profiles',
    category: 'business_tools',
    deliveryType: 'native',
    isEnabled: true,
  },
  {
    featureKey: 'business_analysis',
    name: 'Business Analysis',
    description: 'Business intelligence tools',
    category: 'business_tools',
    deliveryType: 'native',
    isEnabled: true,
  },

  // ===== SMART AUTOMATIONS =====
  {
    featureKey: 'automations',
    name: 'Smart Automations',
    description: 'Pre-built automation workflows',
    category: 'advanced',
    deliveryType: 'native',
    isEnabled: true,
  },
];

async function seedFeatures() {
  console.log('🌱 Seeding comprehensive feature list...');

  try {
    for (const feature of comprehensiveFeatures) {
      await db.insert(features).values(feature).onConflictDoNothing();
      console.log(`✓ ${feature.name}`);
    }

    console.log(`\n✅ Successfully seeded ${comprehensiveFeatures.length} features!`);
  } catch (error) {
    console.error('❌ Error seeding features:', error);
    throw error;
  }
}

// Run the seed if called directly
if (require.main === module) {
  seedFeatures()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}

export { seedFeatures, comprehensiveFeatures };
