-- ============================================================================
-- Remote Applied Migration (Reconciliation)
-- ============================================================================
-- Version: 20260418232000
--
-- This migration was applied directly on the remote Supabase database
-- and did not exist as a local file at the time of reconciliation (2026-05-24).
-- 
-- Created to keep local migration history in sync with production.
-- No statements — changes already exist remotely.
-- ============================================================================

-- (Placeholder - applied on remote)
